"""
download_ai_text_detection.py
------------------------------
Dataset: GPT-2 Output Dataset (OpenAI)
Publicly downloadable without authentication from OpenAI's Azure blob mirror.
Contains matched "webtext" (human-written, GPT-2 training source) and
"small-117M" (machine-generated by GPT-2) splits, ideal for building an
AI-vs-human text detection benchmark.
"""

import sys
from pathlib import Path

sys.path.append(str(Path(__file__).resolve().parents[2]))
from src.download.base_downloader import BaseDownloader, ManualDownloadRequired
from src.utils.io_utils import load_config
from src.utils.logging_utils import get_logger

logger = get_logger(__name__)


class AiTextDetectionDownloader(BaseDownloader):
    def __init__(self, cfg: dict):
        ds_cfg = cfg["datasets"]["ai_text_detection"]
        super().__init__(name=ds_cfg["name"], raw_subdir=ds_cfg["raw_subdir"])
        self.base_url = ds_cfg["base_url"]
        self.files = ds_cfg["files"]

    def _manual_instructions(self) -> str:
        file_list = "\n".join(f"  - {self.base_url}/{f}" for f in self.files)
        return f"""
Dataset: {self.name}
Official repo: https://github.com/openai/gpt-2-output-dataset

Manual fallback (no authentication required, just direct URLs):
{file_list}

Download each file (e.g. via browser or `curl -O <url>`) and place them into:
  {self.raw_dir}/
""".strip()

    def download(self):
        try:
            for fname in self.files:
                url = f"{self.base_url}/{fname}"
                self.http_download(url, fname)
        except Exception as e:
            logger.error(f"[{self.name}] Automated download failed: {e}")
            self.report_manual_download(self._manual_instructions())


if __name__ == "__main__":
    cfg = load_config()
    downloader = AiTextDetectionDownloader(cfg)
    try:
        downloader.download()
    except ManualDownloadRequired:
        sys.exit(1)
